export const symbolMap = {
  "!": "Exclamation",
  '"': "DoubleQuotes",
  "#": "Hash",
  $: "Dollar",
  "%": "Percent",
  "&": "And",
  "'": "SingleQuote",
  "(": "OpenBracket",
  ")": "CloseBracket",
  "*": "Asterisk",
  "+": "Plus",
  ",": "Comma",
  "-": "Hyphen",
  ".": "Dot",
  "/": "Slash",
  ":": "Colon",
  ";": "Semicolon",
  "<": "LessThan",
  "=": "Equal",
  ">": "GreaterThan",
  "?": "QuestionMark",
  "@": "At",
  "[": "OpenSquareBracket",
  "\\": "Backslash",
  "]": "CloseSquareBracket",
  "^": "Caret",
  _: "Underscore",
  //   "`": "BackTick",
  "{": "OpenCurlyBracket",
  "|": "Pipe",
  "}": "CloseCurlyBracket",
  "~": "Tilde",
};
